"""Type stubs for pygxml — gjson-style XML path queries."""
from typing import (
    Any,
    Iterator,
    Optional,
    Protocol,
    Union,
    overload,
)


class _Buffer(Protocol):
    """Anything implementing the buffer protocol (mmap, bytearray, memoryview)."""
    def __buffer__(self, flags: int) -> memoryview: ...


StrInput = str
BytesInput = bytes
BufferInput = Union[bytearray, memoryview, _Buffer]
XmlInput = Union[StrInput, BytesInput, BufferInput]


def get(data: str, path: str) -> "Result":
    """Run `path` against XML string `data` and return a typed `Result`."""
    ...


def get_bytes(data: bytes, path: str) -> "Result":
    """Run `path` against XML bytes `data` and return a typed `Result`."""
    ...


def get_buffer(data: BufferInput, path: str) -> "Result":
    """Run `path` against a buffer-protocol `data` (mmap, bytearray, memoryview)."""
    ...


def get_many(data: str, paths: list[Union[str, "Path"]]) -> list["Result"]:
    """Run multiple paths against XML string `data` in a single document scan."""
    ...


def get_many_bytes(data: bytes, paths: list[Union[str, "Path"]]) -> list["Result"]:
    """Run multiple paths against XML bytes `data` in a single document scan."""
    ...


def get_many_buffer(data: BufferInput, paths: list[Union[str, "Path"]]) -> list["Result"]:
    """Run multiple paths against a buffer-protocol `data` in a single scan."""
    ...


def parse(data: XmlInput) -> "Result":
    """Wrap `data` in a top-level `Result`. Use `.get(path)` to descend."""
    ...


def validate(data: XmlInput) -> bool:
    """Return True iff `data` is well-formed XML."""
    ...


def compile(path: str) -> "Path":
    """Pre-compile a path for repeated use against many documents."""
    ...


class Result:
    """Typed wrapper around the list of matching values.

    Element matches retain their full XML fragment so `.get(path)` can
    descend further. Scalar matches (attributes, `#text`, counts, modifier
    aggregates) cannot be descended into — `.get(path)` returns an empty
    Result for them.
    """
    def exists(self) -> bool: ...
    @property
    def type_(self) -> Optional[type]: ...
    @property
    def value(self) -> object: ...
    def to_str(self) -> str: ...
    def to_int(self) -> int: ...
    def to_float(self) -> float: ...
    def to_bool(self) -> bool: ...
    def get(self, path: str) -> "Result": ...
    def get_many(self, paths: list[Union[str, "Path"]]) -> list["Result"]: ...
    def keys(self) -> "ResultKeysView": ...
    def values(self) -> "ResultValuesView": ...
    def items(self) -> "ResultItemsView": ...
    def __bool__(self) -> bool: ...
    def __int__(self) -> int: ...
    def __float__(self) -> float: ...
    def __iter__(self) -> Iterator: ...
    def __len__(self) -> int: ...
    @overload
    def __getitem__(self, i: int) -> "Result": ...
    @overload
    def __getitem__(self, i: slice) -> "Result": ...
    @overload
    def __getitem__(self, i: str) -> "Result": ...
    def __eq__(self, other: object) -> bool: ...
    def __repr__(self) -> str: ...


class ResultKeysView:
    """dict.keys()-like view over a DictElement Result."""
    def __iter__(self) -> Iterator[str]: ...
    def __len__(self) -> int: ...
    def __contains__(self, key: object) -> bool: ...
    def __repr__(self) -> str: ...


class ResultValuesView:
    """dict.values()-like view over a DictElement Result."""
    def __iter__(self) -> Iterator["Result"]: ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...


class ResultItemsView:
    """dict.items()-like view over a DictElement Result."""
    def __iter__(self) -> Iterator[tuple[str, "Result"]]: ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...


class Path:
    """Pre-compiled XML path."""
    def get(self, data: str) -> "Result": ...
    def get_bytes(self, data: bytes) -> "Result": ...
    def get_buffer(self, data: BufferInput) -> "Result": ...
    def __repr__(self) -> str: ...
